### ISSUE TITLE
After Ranger implementation "My completed orders" in trading-ui stops displaying information.

### ISSUE THREAD

**Issue by pkucherenk0** [rubykube/peatio-trading-ui#102]
After Ranger implementation "My completed orders" is not sensitive to completed orders made by authorized user. 
![p23](https://user-images.githubusercontent.com/38254545/46060939-86163b00-c16d-11e8-935d-095769fd0dd8.png)

Information about Ranger: https://github.com/rubykube/peatio/blob/master/docs/api/websocket_api.md
Part of trading-ui code that might need changes: https://github.com/rubykube/peatio-trading-ui/blob/1-9-stable/app/assets/javascripts/component_data/member.js.coffee

**Comment by zhangatle** [comment]
i have met the same problem,and  my open orders also can't be shown by websocket,i have to refresh the brower,then the open orders can be shown,how to solve it ?

**Comment by huuhait** [comment]
How to fix it?

**Comment by nantestdeveloper** [comment]
facing same issue.any solution to resolve

**Comment by lfcmpi** [comment]
Same here. Anyone got a fix for open orders?

**Comment by jwaiswa7** [comment]
Guys, am failing to setup ranger, I always have the error 
```/home/joshua/usa/peatio-v-1.9/peatio-core-0.4.5/lib/peatio/command/service.rb:6:in `execute': JWT_PUBLIC_KEY was not specified. (ArgumentError)
	from /home/joshua/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
	from /home/joshua/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/clamp-1.3.0/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /home/joshua/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
	from /home/joshua/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/clamp-1.3.0/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /home/joshua/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
	from /home/joshua/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/clamp-1.3.0/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /home/joshua/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
	from /home/joshua/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:140:in `run'
	from ./bin/peatio:12:in `<main>'```

How do I start ranger

**Comment by jwaiswa7** [comment]
Found a solution, run `bundle exec peatio service start ranger` in an application having the peatio core gem installed. 

Thank me later.
