### ISSUE TITLE
Routing Error The URL you requested was not found. localhost:3000/trading/usdbtc

### ISSUE THREAD

**Issue by dragon28** [rubykube/peatio-trading-ui#111]
Hello People,

Log:

```
~/peatio-trading-ui$ bundle exec rails server -p 4000
WARNING: Use strings for Figaro configuration. false was converted to "false".
=> Booting Puma
=> Rails 5.1.6 application starting in development 
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.3 (ruby 2.5.3-p105), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:4000
Use Ctrl-C to stop
Started GET "/" for 127.0.0.1 at 2018-11-22 21:41:53 +0800
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/templates/rails/welcome/index.html.erb (9.1ms)
Completed 200 OK in 36ms (Views: 15.2ms)


Started GET "/favicon.ico" for 127.0.0.1 at 2018-11-22 21:41:54 +0800
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.6) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.1.6) lib/rails/engine.rb:522:in `call'
puma (3.11.3) lib/puma/configuration.rb:225:in `call'
puma (3.11.3) lib/puma/server.rb:624:in `handle_request'
puma (3.11.3) lib/puma/server.rb:438:in `process_client'
puma (3.11.3) lib/puma/server.rb:302:in `block in run'
puma (3.11.3) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
Started GET "/favicon.ico" for 127.0.0.1 at 2018-11-22 21:42:02 +0800
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.6) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.1.6) lib/rails/engine.rb:522:in `call'
puma (3.11.3) lib/puma/configuration.rb:225:in `call'
puma (3.11.3) lib/puma/server.rb:624:in `handle_request'
puma (3.11.3) lib/puma/server.rb:438:in `process_client'
puma (3.11.3) lib/puma/server.rb:302:in `block in run'
puma (3.11.3) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
Started GET "/trading/:4000" for 127.0.0.1 at 2018-11-22 21:42:16 +0800
Processing by MarketsController#show as HTML
  Parameters: {"market_id"=>":4000"}
Completed 500 Internal Server Error in 2ms


  
URI::InvalidURIError (bad URI(is not URI?): :4000.json):
  
app/controllers/markets_controller.rb:32:in `market_variables_url'
app/controllers/markets_controller.rb:6:in `show'
Started GET "/trading/usdbtc:4000" for 127.0.0.1 at 2018-11-22 21:42:39 +0800
Processing by MarketsController#show as HTML
  Parameters: {"market_id"=>"usdbtc:4000"}
Completed 500 Internal Server Error in 30ms


  
URI::InvalidURIError (query conflicts with opaque):
  
config/initializers/faraday.rb:10:in `run_request'
app/controllers/markets_controller.rb:6:in `show'
```

Trace:

```
app/routers/routing_essentials.rb:6:in `not_found!'
app/routers/black_hole_router.rb:8:in `call'
actionpack (4.2.10) lib/action_dispatch/routing/mapper.rb:51:in `serve'
actionpack (4.2.10) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.10) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.10) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.10) lib/action_dispatch/routing/route_set.rb:817:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
omniauth (1.8.1) lib/omniauth/builder.rb:63:in `call'
bullet (5.7.6) lib/bullet/rack.rb:12:in `call'
rack (1.6.11) lib/rack/etag.rb:24:in `call'
rack (1.6.11) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.11) lib/rack/head.rb:13:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.11) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.11) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.10) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.10) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.10) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.10) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.10) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.10) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.10) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.10) lib/rails/rack/logger.rb:22:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.11) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.11) lib/rack/runtime.rb:18:in `call'
rack (1.6.11) lib/rack/lock.rb:17:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.11) lib/rack/sendfile.rb:113:in `call'
railties (4.2.10) lib/rails/engine.rb:518:in `call'
railties (4.2.10) lib/rails/application.rb:165:in `call'
rack (1.6.11) lib/rack/content_length.rb:15:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

nginx configuration:

```
/etc/nginx/sites-available$ cat peatio 
server {
  server_name      test.com;
  listen           80;
  proxy_set_header Host test.com;

  location ~ ^/(?:trading|trading-ui-assets)\/ {
    proxy_pass http://127.0.0.1:4000;
  }

  location / {
    proxy_pass http://127.0.0.1:3000;
  }
}

```
application.yml

```
~/peatio-trading-ui/config$ cat application.yml
defaults: &defaults

  # Set root URL to Peatio platform. It will be used to fetch variables which is trading interface driven by.
  #PLATFORM_ROOT_URL: http://peatio.tech
  PLATFORM_ROOT_URL: http://test.com
  

  # Set URL where you wan to redirect from trading ui menubar
  #FRONTEND_ROOT_URL: http://peatio.tech
  FRONTEND_ROOT_URL: http://test.com

  # Set to "true" to disable access via unsecured HTTP, send HSTS headers and use secure cookies.
  FORCE_SECURE_CONNECTION: false

  # Customize title of markers page using the variable below:
  #TITLE: PEATIO
  TITLE: Test

  # Customize page metadata like title, description & keywords.
  #METADATA_TITLE:       Peatio Exchange
  #METADATA_DESCRIPTION: The Opensource Cryptocurrency Exchange
  #METADATA_KEYWORDS:    Peatio,Opensource,Exchange,Cryptocurrency
  METADATA_TITLE:       Test Exchange
  METADATA_DESCRIPTION: The Cryptocurrency Exchange
  METADATA_KEYWORDS:    Test,Cryptocurrency Exchange,Exchange,Cryptocurrency

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
```

I hope someone able to lend me a helping hand because I am not sure what have went wrong..

Thanks

**Comment by not-a-dev0** [comment]
https://github.com/not-a-dev0/peatio-trading-ui-guide

**Comment by rastislavcore** [comment]
Same issue. Not sure what will be solution

**Comment by AnythingLinux** [comment]
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

If you are the application owner check the logs for more information.


![Screenshot from 2019-05-14 21-43-17](https://user-images.githubusercontent.com/1058663/57711817-4ca92600-7691-11e9-95a6-7c317b933788.png)
