### ISSUE TITLE
 Completed 500 Internal Server Error in 60055ms Faraday::ConnectionFailed (execution expired): config/initializers/faraday.rb:10:in `run_request' app/controllers/markets_controller.rb:6:in `show'

### ISSUE THREAD

**Issue by not-a-dev0** [rubykube/peatio-trading-ui#120]
Still having issues with the trading-ui

```
WARNING: Use strings for Figaro configuration. false was converted to "false".
=> Booting Puma
=> Rails 5.1.6 application starting in production
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.3 (ruby 2.5.0-p0), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:4000
Use Ctrl-C to stop
Started GET "/trading/usdbtc" for 76.2.42.176 at 2019-01-01 19:21:32 +0000
Processing by MarketsController#show as HTML
  Parameters: {"market_id"=>"usdbtc"}
Completed 500 Internal Server Error in 60055ms

Faraday::ConnectionFailed (execution expired):

config/initializers/faraday.rb:10:in `run_request'
app/controllers/markets_controller.rb:6:in `show'

```

**Comment by jwaiswa7** [comment]
I am having the same issue, how were you able to resolve it.
